### ISSUE TITLE
Error message when using get_user_content

### ISSUE THREAD

**Issue by DrAndrewLedbetter** [ivan-rivera/RedditExtractor#30] opened 2022-08-08 15:44 UTC
I am trying to pull some user information from Reddit using get_user_content. When I do so, I get an error message. For example, when running the example code in the function documentation:

> test <- get_user_content(c("memes", "nationalgeographic"))
parsing user memes...
parsing URLs on page 1...
Error in value[[3L]](cond) : 
  Cannot read from Reddit, check your inputs or internet connection
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'https://www.reddit.com/user/memes.json?limit=100': HTTP status was '429 Unknown Error'

The same error occurs if I search for just one username, and also occurs for other functions in the package (e.g., find_subreddits). I've tried the code on two different laptops (both Windows 10) and at two different Internet access points, and received the same error. Also, I tried reverting to version 2.1.5 of RedditExtractoR, and that worked fine for pulling information from Reddit, with no error messages. I'm running R version 4.2.1. Thanks for any help!

**Comment by ivan-rivera** [comment] 2022-08-08 20:03
Hi Andrew,

I'm afraid that I cannot replicate your problem. When I run `test <- get_user_content(c("memes", "nationalgeographic"))`, the command finishes successfully. HTTP status 429 usually means "too many requests", but the throttling logic appears to be working correctly as I've just checked. Can you access `https://www.reddit.com/user/memes.json?limit=100` via your browser? If so, then what do you get when you run `readLines(x)` (where `x` is pointing at this URL)?

**Comment by DrAndrewLedbetter** [comment] 2022-08-08 22:29
Thank you for the quick reply!

So the upshot is--I solved the problem by trying to execute the code in
RStudio (I know, I'm weird using vanilla R much of the time). Why that
fixes it, I don't know. In case any of this is helpful:

Here's a screenshot when I access the URL through my browser. It appears to
be drawing the data correctly from the API.

[image: image.png]

Running readLines in vanilla R yields the same error message, but in
RStudio it returns correctly.

Much thanks--

Andrew


Andrew M. Ledbetter, Ph.D.
Professor, Department of Communication Studies
Texas Christian University
@dr_ledbetter


Co-author of A First Look at Communication Theory (10th ed.)
www.afirstlook.com
@commtheorybook

**Comment by ivan-rivera** [comment] 2022-08-08 22:54
Thanks for the update! Not sure what the problem is, but it appears to be unrelated to the package, so I'm closing this issue. Glad you've found the solution though

**Closed by ivan-rivera** 2022-08-08 22:54 UTC
Labels: bug
