### ISSUE TITLE
Can't get results for more than one keywords

### ISSUE THREAD

**Issue by sadettindemirel** [ivan-rivera/RedditExtractor#29] opened 2022-06-02 11:06 UTC
**Describe the bug**
I can't scrape reddit contents when I want to scrape more than one keyword with **find_thread_urls** function. With two different keyword, which I put it like this find_thread_urls (keywords = c("dummya", "dummyb"), subreddit = "Turkey", sort_by = "new")

**To Reproduce**

Use find_thread_urls and define keywords argument with two or more keywords

**Expected behavior**

Normally it should bring the results regarding the two keywords

**Desktop (please complete the following information):**
I am using windows 10 OS and R version 4.1.3 with R studio IDE

**Comment by ivan-rivera** [comment] 2022-06-02 18:59
@sadettindemirel the keywords parameter is a string, not a vector, so if you want to look for multiple keywords, then you need to call this function multiple times in a loop. Closing this, since it's not a bug, it's the expected behaviour.

**Closed by ivan-rivera** 2022-06-02 18:59 UTC
Labels: bug
